name: 기능 요청
description: 새로운 기능 제안을 남겨주세요.
title: "[기능] 제목을 입력하세요"
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: 문제/배경
      description: 어떤 문제가 있거나 어떤 필요가 있는지 설명해주세요.
      placeholder: 예) 사용자 권한에 따라 노래 목록 필터가 필요합니다.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 제안하는 해결책
      description: 구현 아이디어나 접근 방식을 구체적으로 적어주세요.
      placeholder: 예) Role 기반으로 /songs 엔드포인트에 파라미터 추가
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 대안(선택)
      description: 고려했던 대안이나 다른 방법이 있다면 적어주세요.
    validations:
      required: false
  - type: textarea
    id: scope
    attributes:
      label: 범위/영향(선택)
      description: 영향을 받는 도메인, 서비스, API를 적어주세요.
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: 수용 기준(AC)
      description: 완료로 간주하기 위한 명확한 기준을 적어주세요.
      placeholder: |
        - [ ] 권한 ROLE_ADMIN인 경우 모든 노래 조회 가능
        - [ ] ROLE_USER는 본인 작성 노래만 조회
    validations:
      required: true
  - type: checkboxes
    id: confirmations
    attributes:
      label: 확인 사항
      options:
        - label: 중복 이슈가 아닌지 검색했습니다.
          required: true
        - label: 민감한 정보가 포함되지 않았습니다.
          required: true
