name: 기타 이슈
description: 위 카테고리에 해당하지 않는 기타 이슈입니다.
title: "[기타] 제목을 입력하세요"
labels: ["needs-triage"]
assignees: []
body:
  - type: textarea
    id: details
    attributes:
      label: 상세 내용
      description: 이슈의 목적과 필요 정보를 자유롭게 적어주세요.
    validations:
      required: true
  - type: checkboxes
    id: confirmations
    attributes:
      label: 확인 사항
      options:
        - label: 중복 이슈가 아닌지 검색했습니다.
          required: true
