name: 개선/작업 이슈
description: 리팩토링, 테스트 보강, 설정 변경 등 일반 작업 이슈입니다.
title: "[작업] 제목을 입력하세요"
labels: ["task", "needs-triage"]
assignees: []
body:
  - type: textarea
    id: context
    attributes:
      label: 배경/컨텍스트
      description: 왜 이 작업이 필요한지 배경을 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: 목표/완료 정의
      description: 무엇이 완료인지(DoD)를 적어주세요.
      placeholder: |
        - [ ] 불필요한 종속성 제거
        - [ ] 커버리지 80% 이상
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 영향 범위(선택)
      description: 영향을 받는 모듈/서비스/배포 사항
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: 작업 체크리스트(선택)
      options:
        - label: 코드 변경에 대한 테스트를 작성/수정했습니다.
          required: false
        - label: 문서/CHANGELOG를 업데이트했습니다.
          required: false
        - label: 성능/보안 영향도를 검토했습니다.
          required: false
